// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: ml_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeAudioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioData     []byte                 `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeAudioRequest) Reset() {
	*x = AnalyzeAudioRequest{}
	mi := &file_ml_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeAudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeAudioRequest) ProtoMessage() {}

func (x *AnalyzeAudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeAudioRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeAudioRequest) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeAudioRequest) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *AnalyzeAudioRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type AnalyzeAudioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	MoodEnergy    float32                `protobuf:"fixed32,2,opt,name=mood_energy,json=moodEnergy,proto3" json:"mood_energy,omitempty"`
	MoodValence   float32                `protobuf:"fixed32,3,opt,name=mood_valence,json=moodValence,proto3" json:"mood_valence,omitempty"`
	MoodTempo     float32                `protobuf:"fixed32,4,opt,name=mood_tempo,json=moodTempo,proto3" json:"mood_tempo,omitempty"`
	MoodTexture   float32                `protobuf:"fixed32,5,opt,name=mood_texture,json=moodTexture,proto3" json:"mood_texture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeAudioResponse) Reset() {
	*x = AnalyzeAudioResponse{}
	mi := &file_ml_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeAudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeAudioResponse) ProtoMessage() {}

func (x *AnalyzeAudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeAudioResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeAudioResponse) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeAudioResponse) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *AnalyzeAudioResponse) GetMoodEnergy() float32 {
	if x != nil {
		return x.MoodEnergy
	}
	return 0
}

func (x *AnalyzeAudioResponse) GetMoodValence() float32 {
	if x != nil {
		return x.MoodValence
	}
	return 0
}

func (x *AnalyzeAudioResponse) GetMoodTempo() float32 {
	if x != nil {
		return x.MoodTempo
	}
	return 0
}

func (x *AnalyzeAudioResponse) GetMoodTexture() float32 {
	if x != nil {
		return x.MoodTexture
	}
	return 0
}

type RefineEmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseEmbedding []float32              `protobuf:"fixed32,1,rep,packed,name=base_embedding,json=baseEmbedding,proto3" json:"base_embedding,omitempty"`
	Energy        float32                `protobuf:"fixed32,2,opt,name=energy,proto3" json:"energy,omitempty"`
	Valence       float32                `protobuf:"fixed32,3,opt,name=valence,proto3" json:"valence,omitempty"`
	Tempo         float32                `protobuf:"fixed32,4,opt,name=tempo,proto3" json:"tempo,omitempty"`
	Texture       float32                `protobuf:"fixed32,5,opt,name=texture,proto3" json:"texture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefineEmbeddingRequest) Reset() {
	*x = RefineEmbeddingRequest{}
	mi := &file_ml_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefineEmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefineEmbeddingRequest) ProtoMessage() {}

func (x *RefineEmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefineEmbeddingRequest.ProtoReflect.Descriptor instead.
func (*RefineEmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{2}
}

func (x *RefineEmbeddingRequest) GetBaseEmbedding() []float32 {
	if x != nil {
		return x.BaseEmbedding
	}
	return nil
}

func (x *RefineEmbeddingRequest) GetEnergy() float32 {
	if x != nil {
		return x.Energy
	}
	return 0
}

func (x *RefineEmbeddingRequest) GetValence() float32 {
	if x != nil {
		return x.Valence
	}
	return 0
}

func (x *RefineEmbeddingRequest) GetTempo() float32 {
	if x != nil {
		return x.Tempo
	}
	return 0
}

func (x *RefineEmbeddingRequest) GetTexture() float32 {
	if x != nil {
		return x.Texture
	}
	return 0
}

type RefineEmbeddingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedding     []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefineEmbeddingResponse) Reset() {
	*x = RefineEmbeddingResponse{}
	mi := &file_ml_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefineEmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefineEmbeddingResponse) ProtoMessage() {}

func (x *RefineEmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefineEmbeddingResponse.ProtoReflect.Descriptor instead.
func (*RefineEmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{3}
}

func (x *RefineEmbeddingResponse) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_ml_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{4}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_ml_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_ml_service_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ml_service_proto protoreflect.FileDescriptor

const file_ml_service_proto_rawDesc = "" +
	"\n" +
	"\x10ml_service.proto\x12\x05evoke\"L\n" +
	"\x13AnalyzeAudioRequest\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x01 \x01(\fR\taudioData\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"\xba\x01\n" +
	"\x14AnalyzeAudioResponse\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\x12\x1f\n" +
	"\vmood_energy\x18\x02 \x01(\x02R\n" +
	"moodEnergy\x12!\n" +
	"\fmood_valence\x18\x03 \x01(\x02R\vmoodValence\x12\x1d\n" +
	"\n" +
	"mood_tempo\x18\x04 \x01(\x02R\tmoodTempo\x12!\n" +
	"\fmood_texture\x18\x05 \x01(\x02R\vmoodTexture\"\xa1\x01\n" +
	"\x16RefineEmbeddingRequest\x12%\n" +
	"\x0ebase_embedding\x18\x01 \x03(\x02R\rbaseEmbedding\x12\x16\n" +
	"\x06energy\x18\x02 \x01(\x02R\x06energy\x12\x18\n" +
	"\avalence\x18\x03 \x01(\x02R\avalence\x12\x14\n" +
	"\x05tempo\x18\x04 \x01(\x02R\x05tempo\x12\x18\n" +
	"\atexture\x18\x05 \x01(\x02R\atexture\"7\n" +
	"\x17RefineEmbeddingResponse\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\"\x14\n" +
	"\x12HealthCheckRequest\"I\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xec\x01\n" +
	"\tMLService\x12G\n" +
	"\fAnalyzeAudio\x12\x1a.evoke.AnalyzeAudioRequest\x1a\x1b.evoke.AnalyzeAudioResponse\x12P\n" +
	"\x0fRefineEmbedding\x12\x1d.evoke.RefineEmbeddingRequest\x1a\x1e.evoke.RefineEmbeddingResponse\x12D\n" +
	"\vHealthCheck\x12\x19.evoke.HealthCheckRequest\x1a\x1a.evoke.HealthCheckResponseB Z\x1egithub.com/evoke/backend/protob\x06proto3"

var (
	file_ml_service_proto_rawDescOnce sync.Once
	file_ml_service_proto_rawDescData []byte
)

func file_ml_service_proto_rawDescGZIP() []byte {
	file_ml_service_proto_rawDescOnce.Do(func() {
		file_ml_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ml_service_proto_rawDesc), len(file_ml_service_proto_rawDesc)))
	})
	return file_ml_service_proto_rawDescData
}

var file_ml_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ml_service_proto_goTypes = []any{
	(*AnalyzeAudioRequest)(nil),     // 0: evoke.AnalyzeAudioRequest
	(*AnalyzeAudioResponse)(nil),    // 1: evoke.AnalyzeAudioResponse
	(*RefineEmbeddingRequest)(nil),  // 2: evoke.RefineEmbeddingRequest
	(*RefineEmbeddingResponse)(nil), // 3: evoke.RefineEmbeddingResponse
	(*HealthCheckRequest)(nil),      // 4: evoke.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 5: evoke.HealthCheckResponse
}
var file_ml_service_proto_depIdxs = []int32{
	0, // 0: evoke.MLService.AnalyzeAudio:input_type -> evoke.AnalyzeAudioRequest
	2, // 1: evoke.MLService.RefineEmbedding:input_type -> evoke.RefineEmbeddingRequest
	4, // 2: evoke.MLService.HealthCheck:input_type -> evoke.HealthCheckRequest
	1, // 3: evoke.MLService.AnalyzeAudio:output_type -> evoke.AnalyzeAudioResponse
	3, // 4: evoke.MLService.RefineEmbedding:output_type -> evoke.RefineEmbeddingResponse
	5, // 5: evoke.MLService.HealthCheck:output_type -> evoke.HealthCheckResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ml_service_proto_init() }
func file_ml_service_proto_init() {
	if File_ml_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ml_service_proto_rawDesc), len(file_ml_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ml_service_proto_goTypes,
		DependencyIndexes: file_ml_service_proto_depIdxs,
		MessageInfos:      file_ml_service_proto_msgTypes,
	}.Build()
	File_ml_service_proto = out.File
	file_ml_service_proto_goTypes = nil
	file_ml_service_proto_depIdxs = nil
}
