// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// MLServiceClient is the client API for MLService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MLServiceClient interface {
	AnalyzeAudio(ctx context.Context, in *AnalyzeAudioRequest, opts ...grpc.CallOption) (*AnalyzeAudioResponse, error)
	RefineEmbedding(ctx context.Context, in *RefineEmbeddingRequest, opts ...grpc.CallOption) (*RefineEmbeddingResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type mLServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMLServiceClient(cc grpc.ClientConnInterface) MLServiceClient {
	return &mLServiceClient{cc}
}

func (c *mLServiceClient) AnalyzeAudio(ctx context.Context, in *AnalyzeAudioRequest, opts ...grpc.CallOption) (*AnalyzeAudioResponse, error) {
	out := new(AnalyzeAudioResponse)
	err := c.cc.Invoke(ctx, "/evoke.MLService/AnalyzeAudio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLServiceClient) RefineEmbedding(ctx context.Context, in *RefineEmbeddingRequest, opts ...grpc.CallOption) (*RefineEmbeddingResponse, error) {
	out := new(RefineEmbeddingResponse)
	err := c.cc.Invoke(ctx, "/evoke.MLService/RefineEmbedding", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/evoke.MLService/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MLServiceServer is the server API for MLService service.
// All implementations must embed UnimplementedMLServiceServer
// for forward compatibility
type MLServiceServer interface {
	AnalyzeAudio(context.Context, *AnalyzeAudioRequest) (*AnalyzeAudioResponse, error)
	RefineEmbedding(context.Context, *RefineEmbeddingRequest) (*RefineEmbeddingResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedMLServiceServer()
}

// UnimplementedMLServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMLServiceServer struct {
}

func (UnimplementedMLServiceServer) AnalyzeAudio(context.Context, *AnalyzeAudioRequest) (*AnalyzeAudioResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeAudio not implemented")
}
func (UnimplementedMLServiceServer) RefineEmbedding(context.Context, *RefineEmbeddingRequest) (*RefineEmbeddingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefineEmbedding not implemented")
}
func (UnimplementedMLServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedMLServiceServer) mustEmbedUnimplementedMLServiceServer() {}

// UnsafeMLServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MLServiceServer will
// result in compilation errors.
type UnsafeMLServiceServer interface {
	mustEmbedUnimplementedMLServiceServer()
}

func RegisterMLServiceServer(s grpc.ServiceRegistrar, srv MLServiceServer) {
	s.RegisterService(&MLService_ServiceDesc, srv)
}

func _MLService_AnalyzeAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeAudioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).AnalyzeAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evoke.MLService/AnalyzeAudio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).AnalyzeAudio(ctx, req.(*AnalyzeAudioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLService_RefineEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefineEmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).RefineEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evoke.MLService/RefineEmbedding",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).RefineEmbedding(ctx, req.(*RefineEmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/evoke.MLService/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MLService_ServiceDesc is the grpc.ServiceDesc for MLService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MLService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "evoke.MLService",
	HandlerType: (*MLServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeAudio",
			Handler:    _MLService_AnalyzeAudio_Handler,
		},
		{
			MethodName: "RefineEmbedding",
			Handler:    _MLService_RefineEmbedding_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _MLService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ml_service.proto",
}
