# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ml_service_pb2 as ml__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ml_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MLServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeAudio = channel.unary_unary(
                '/evoke.MLService/AnalyzeAudio',
                request_serializer=ml__service__pb2.AnalyzeAudioRequest.SerializeToString,
                response_deserializer=ml__service__pb2.AnalyzeAudioResponse.FromString,
                _registered_method=True)
        self.RefineEmbedding = channel.unary_unary(
                '/evoke.MLService/RefineEmbedding',
                request_serializer=ml__service__pb2.RefineEmbeddingRequest.SerializeToString,
                response_deserializer=ml__service__pb2.RefineEmbeddingResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/evoke.MLService/HealthCheck',
                request_serializer=ml__service__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=ml__service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class MLServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefineEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeAudio,
                    request_deserializer=ml__service__pb2.AnalyzeAudioRequest.FromString,
                    response_serializer=ml__service__pb2.AnalyzeAudioResponse.SerializeToString,
            ),
            'RefineEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.RefineEmbedding,
                    request_deserializer=ml__service__pb2.RefineEmbeddingRequest.FromString,
                    response_serializer=ml__service__pb2.RefineEmbeddingResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ml__service__pb2.HealthCheckRequest.FromString,
                    response_serializer=ml__service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'evoke.MLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('evoke.MLService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MLService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evoke.MLService/AnalyzeAudio',
            ml__service__pb2.AnalyzeAudioRequest.SerializeToString,
            ml__service__pb2.AnalyzeAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefineEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evoke.MLService/RefineEmbedding',
            ml__service__pb2.RefineEmbeddingRequest.SerializeToString,
            ml__service__pb2.RefineEmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/evoke.MLService/HealthCheck',
            ml__service__pb2.HealthCheckRequest.SerializeToString,
            ml__service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
