# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ml_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ml_service.proto\x12\x05\x65voke\"9\n\x13\x41nalyzeAudioRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x0e\n\x06\x66ormat\x18\x02 \x01(\t\"~\n\x14\x41nalyzeAudioResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\x12\x13\n\x0bmood_energy\x18\x02 \x01(\x02\x12\x14\n\x0cmood_valence\x18\x03 \x01(\x02\x12\x12\n\nmood_tempo\x18\x04 \x01(\x02\x12\x14\n\x0cmood_texture\x18\x05 \x01(\x02\"q\n\x16RefineEmbeddingRequest\x12\x16\n\x0e\x62\x61se_embedding\x18\x01 \x03(\x02\x12\x0e\n\x06\x65nergy\x18\x02 \x01(\x02\x12\x0f\n\x07valence\x18\x03 \x01(\x02\x12\r\n\x05tempo\x18\x04 \x01(\x02\x12\x0f\n\x07texture\x18\x05 \x01(\x02\",\n\x17RefineEmbeddingResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\"\x14\n\x12HealthCheckRequest\"7\n\x13HealthCheckResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xec\x01\n\tMLService\x12G\n\x0c\x41nalyzeAudio\x12\x1a.evoke.AnalyzeAudioRequest\x1a\x1b.evoke.AnalyzeAudioResponse\x12P\n\x0fRefineEmbedding\x12\x1d.evoke.RefineEmbeddingRequest\x1a\x1e.evoke.RefineEmbeddingResponse\x12\x44\n\x0bHealthCheck\x12\x19.evoke.HealthCheckRequest\x1a\x1a.evoke.HealthCheckResponseB Z\x1egithub.com/evoke/backend/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\036github.com/evoke/backend/proto'
  _globals['_ANALYZEAUDIOREQUEST']._serialized_start=27
  _globals['_ANALYZEAUDIOREQUEST']._serialized_end=84
  _globals['_ANALYZEAUDIORESPONSE']._serialized_start=86
  _globals['_ANALYZEAUDIORESPONSE']._serialized_end=212
  _globals['_REFINEEMBEDDINGREQUEST']._serialized_start=214
  _globals['_REFINEEMBEDDINGREQUEST']._serialized_end=327
  _globals['_REFINEEMBEDDINGRESPONSE']._serialized_start=329
  _globals['_REFINEEMBEDDINGRESPONSE']._serialized_end=373
  _globals['_HEALTHCHECKREQUEST']._serialized_start=375
  _globals['_HEALTHCHECKREQUEST']._serialized_end=395
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=397
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=452
  _globals['_MLSERVICE']._serialized_start=455
  _globals['_MLSERVICE']._serialized_end=691
# @@protoc_insertion_point(module_scope)
